name: Build Windows x64

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.94.0
          targets: x86_64-pc-windows-msvc

      - name: Build
        run: cargo build --release --package jixel --target x86_64-pc-windows-msvc

      - name: Rename binary
        shell: pwsh
        run: |
          Copy-Item `
            "target\x86_64-pc-windows-msvc\release\jixel.exe" `
            "jixel.exe"

      - name: Upload jixel.exe
        uses: actions/upload-artifact@v7
        with:
          name: jixel-windows-x64
          path: jixel.exe
          if-no-files-found: error
